(() => {
  let token=sessionStorage.getItem('hubAccessToken') || '';
  const el=id=>document.getElementById(id);
  async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401){token='';sessionStorage.removeItem('hubAccessToken');el('account').hidden=true;el('login').hidden=false;}throw Error(d.error||'请求失败');}return d;}
  async function run(fn){el('notice').textContent='';try{await fn();}catch(e){el('notice').textContent=e.message;}}
  async function refresh(){if(!token)return;const [me,products,agents,bills]=await Promise.all([api('/v1/me'),api('/v1/products'),api('/v1/agents'),api('/v1/billing')]);el('login').hidden=true;el('account').hidden=false;el('identity').textContent=me.user.email;const selected=el('product').value;el('product').replaceChildren();for(const p of products.items){const o=document.createElement('option');o.value=p.product;o.textContent=p.name;o.dataset.subscribable=String(p.subscriptionAvailable);el('product').append(o);}if([...el('product').options].some(o=>o.value===selected))el('product').value=selected;el('product').dispatchEvent(new Event('change'));el('agents').replaceChildren();for(const a of agents.items){const p=document.createElement('p');p.textContent=a.product+' · '+a.status;if(a.botUsername){const link=document.createElement('a');link.textContent=' 打开 Telegram';link.href='https://t.me/'+encodeURIComponent(a.botUsername);link.target='_blank';link.rel='noopener';p.append(link);}el('agents').append(p);}if(!agents.items.length)el('agents').textContent='尚未开通助手';el('bills').replaceChildren();for(const b of bills.items){const p=document.createElement('p');p.textContent=b.product+' · '+b.status;el('bills').append(p);}el('portal').disabled=!bills.items.some(b=>b.subscriptionId||b.checkoutSessionId);}
  el('product').onchange=()=>{el('subscribe').disabled=el('product').selectedOptions[0]?.dataset.subscribable!=='true';};
  el('redeem').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;run(async()=>{await api('/v1/invite-codes/redeem',{product:el('product').value,inviteCode:el('code').value.trim()});el('code').value='';await refresh();}).finally(()=>b.disabled=false);};
  el('subscribe').onclick=()=>run(async()=>{const r=await api('/v1/billing/checkout-sessions',{product:el('product').value,quantity:1});location.assign(r.url);});
  el('portal').onclick=()=>run(async()=>{const r=await api('/v1/billing/portal-sessions',{});location.assign(r.url);});
  el('refresh').onclick=()=>run(refresh);
  el('logout').onclick=()=>run(async()=>{await api('/v1/auth/logout',{});sessionStorage.removeItem('hubAccessToken');token='';location.reload();});
  async function init(){const cfg=await api('/v1/auth/info');if(!cfg.googleClientId){el('notice').textContent='Google 登录尚未配置';return;}let attempts=0;const timer=setInterval(()=>{if(!window.google?.accounts?.id){if(++attempts>100){clearInterval(timer);el('notice').textContent='Google 登录组件未加载，请检查网络后刷新';}return;}clearInterval(timer);google.accounts.id.initialize({client_id:cfg.googleClientId,callback:r=>run(async()=>{const result=await api('/v1/auth/google',{id_token:r.credential});token=result.accessToken;sessionStorage.setItem('hubAccessToken',token);await refresh();})});google.accounts.id.renderButton(el('login'),{theme:'outline',size:'large'});},100);await refresh();}
  run(init);
})();
